# Generated by Django 2.2.6 on 2019-11-06 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconfaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='modifield',
            field=models.DateField(auto_now=True, verbose_name='Modificado em'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Descrição')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reconfaces.Dados')),
            ],
        ),
    ]
